services:
  ubuntu1:
    build:
      context: .
      dockerfile: ubuntu-ansible-root.Dockerfile
    ports:
      - "2221:22"
      - "8081:80"
    container_name: docker-11

  ubuntu2:
    build:
      context: .
      dockerfile: ubuntu-ansible-root.Dockerfile
    ports:
      - "2222:22"
    container_name: docker-21