- name: Copy and build
  hosts: all
  tasks:
    - name: Install gcc and make
      ansible.builtin.apt:
        name: gcc
    - name: Copy code
      ansible.builtin.copy:
        src: main.c
        dest: /tmp/main.c
    - name: Compile
      ansible.builtin.shell: gcc {{COMPILE_FLAGS | default("")}} -o /tmp/program /tmp/main.c
    - name: Run
      ansible.builtin.shell: /tmp/program
      register: program_output
    - name: Show output
      ansible.builtin.debug:
        msg: "Program z {{inventory_hostname}} powiedzial: {{program_output.stdout}}"


