all:
  hosts:
    docker11:
      ansible_host: localhost
      ansible_port: 2221
      ansible_user: root
      ansible_ssh_pass: root
    docker21:
      ansible_host: localhost
      ansible_port: 2222
      ansible_user: root
      ansible_ssh_pass: root
one:
  hosts:
    docker11:
