apiVersion: v1
kind: Service
metadata:
  name: ack-app-service
spec:
  type: LoadBalancer
  selector:
    app: ack-app     # loadbalancer na aplikacji z taka etykieta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
