apiVersion: v1
kind: Service
metadata:
  name: backend-canary-svc
spec:
  clusterIP: None
  selector:
    app: backend-canary
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-canary
  template:
    metadata:
      labels:
        app: backend-canary
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
        ports:
        - containerPort: 80